# .streamlit/config.toml

[theme]
# Color principal (Guinda institucional)
primaryColor = "#9F2241"

# Fondo general (Gris muy sutil, casi blanco, se ve más limpio)
backgroundColor = "#FFFFFF"

# Fondo de los paneles laterales (Sidebar) y tarjetas
secondaryBackgroundColor = "#F0F2F6"

# Color del texto (Gris oscuro elegante, mejor para la vista que negro puro)
textColor = "#31333F"

# Tipografía moderna
font = "sans serif"

[client]
# Ocultar errores crudos de python al usuario final
showErrorDetails = false

[server]
# Aumentar límite de subida para archivos pesados y evitar cortes de conexión
maxUploadSize = 500